name: Masking between Jobs
# run-name: Masking Between Jobs
on:
 workflow_dispatch:
jobs:
  secret-generator:
    runs-on: ubuntu-latest
    outputs:
     handle: ${{ steps.generate-secret.outputs.handle }}
    env:
     ENCRYPT_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }}
    steps:
    - name: generate secret
      id: generate-secret
      run: |
        GENERATED_SECRET=$((RANDOM))
        echo "::add-mask::$GENERATED_SECRET"
        SECRET_HANDLE=$(gpg --symmetric --batch --passphrase "$ENCRYPT_PASSPHRASE" --output - <(echo "$GENERATED_SECRET") | base64 -w0)
        echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"

  secret-consumer:
    runs-on: ubuntu-latest
    needs: secret-generator
    env:
     ENCRYPT_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }}
    steps:
    - name: use secret
      id: use-secret
      run: |
        echo "::add-mask::${{ needs.secret-generator.outputs.handle }}"


    

     
