name: Masking Test
on: workflow_dispatch

jobs:
  secret-consumer:
    runs-on: ubuntu-latest
    env:
     ENCRYPT_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }}
    steps:
    - name: use secret
      uses: https://github.com/appusamymanjanaicker/test_repo/blob/main/.github/workflows/reusable-workflow.yml@main
      with:
       config-path: PASS

