name: Masking Test
on: workflow_dispatch

jobs:
  secret-consumer:
    runs-on: ubuntu-latest
    env:
     ENCRYPT_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@V2
      
    - name: use secret
      uses: ./.github/workflows/reusable-workflow.yml
      with:
       config-path: PASS

