name: Masking Test
on: workflow_dispatch
permissions:
 contents: write
 packages: write
 checks: write

jobs:
  secret-consumer:
    runs-on: ubuntu-latest
    env:
     ENCRYPT_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: ./.github/workflows/reusable-workflow.yml
      with:
       config-path: TEST

