name:  Get Secrets
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    env:
     ENCRYPT_PASSPHRASE: ${{ secrets.REPO_PASSPHRASE }}
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
    - name: generate secret
      id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET=$((RANDOM))
        echo "::add-mask::$GENERATED_SECRET"
        SECRET_HANDLE=$(gpg --symmetric --batch --passphrase "$ENCRYPT_PASSPHRASE" --output - <(echo "$GENERATED_SECRET") | base64 -w0)
        echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"
